project:
  type: website
  output-dir: docs
website:
  title: "R Görselleştirme Sitesi"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa
      - href: Base_R_verilerin_gorsellestirilmesi.qmd
        text: Görselleştirme
format:
  html:
    theme: cosmo
    code-fold: true
