project:
  type: website
  output-dir: docs

website:
  title: "R Görselleştirme"
  navbar:
    left:
      - href: index.qmd
        text: Anasayfa
      - href: Base_R_verilerin_gorsellestirilmesi.qmd
        text: Base R Grafikler
      - href: ggplot2.qmd
        text: ggplot2
